### ISSUE TITLE
A possibly improved implementation.

### ISSUE THREAD

**Issue by cparks1000000** [oegedijk/blog#15]
I tried to improve the code a bit so that it handles subclasses and imports. It should also handle Iterables with limitations. The code is not tested fully, but it it seems to work. If you would be kind enough to test it, I give you my permission to upload it to your blog. I don't even need credit. However, if you spot a bug or find any improvement, please let me know. Code follows:

------------------------------------------------------------------------------------------------------------------------------------------

import sys
import types as t

from numpy import ndarray
from torch import Tensor

import __main__
import inspect

from pathlib import Path
from typing import Any, Optional, Set, Dict, Tuple, runtime_checkable, Protocol, TypeVar, List, Iterable

import dill  # type: ignore
import torch

def mainify(obj: object, max_depth: int = 100) -> None:
    _mainify(obj, 0, max_depth)

def _mainify(obj: object, depth: int, max_depth: int) -> object:
    if isinstance(obj, _toxic_types): return obj
    if depth > max_depth: return obj
    obj = _check_recursion(obj, depth, max_depth)
    if not hasattr(obj, "__module__") or obj.__module__ in _builtins: return obj
    _add_to_main(obj)
    if is_named(obj): obj = getattr(__main__, obj.__name__)
    else:
        obj.__class__ = getattr(__main__, obj.__class__.__name__)
        for key, value in obj.__dict__.items():
            temp: object = _mainify(value, depth, max_depth)
            setattr(obj, key, temp)
    return obj

def is_named(obj: object) -> bool: return hasattr(obj, "__name__")

def _add_to_main(obj: object):
    module_source = inspect.getsource(inspect.getmodule(obj))
    exec(compile(module_source, '<string>', 'exec'), __main__.__dict__)
    _already_copied.add(obj.__module__)

@runtime_checkable
class ListLike(Protocol[S]):
    def __setitem__(self, __key: int, __value: S) -> None: ...
    def __getitem__(self, __key: int) -> S: ...
    def __len__(self) -> int: ...

@runtime_checkable
class DictLike(Protocol[T, S]):
    def __setitem__(self, __key: T, __value: S) -> None: ...
    def __getitem__(self, __key: T) -> S: ...
    def items(self) -> List[Tuple[T, S]]: ...

def _check_recursion(obj: object, depth: int, max_depth: int) -> object:
    if not isinstance(obj, Iterable) or isinstance(obj, _toxic_iterables): return obj
    the_class = obj.__class__
    if isinstance(obj, DictLike):
        for key, value in obj.items(): obj[key] = _mainify(value, depth + 1, max_depth)
    if isinstance(obj, Tuple): obj = list(obj)
    if isinstance(obj, ListLike):
        for i in range(len(obj)): obj[i] = _mainify(obj[i], depth + 1, max_depth)
    return obj if obj.__class__ == the_class else the_class(obj)  # type: ignore[arg-type]

**Comment by oegedijk** [comment]
Hi, sounds like a good topic for a gist or you can leave it as a comment!
